apiVersion: tekton.dev/v1beta1
metadata:
  generateName: buildah-run
kind: PipelineRun
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: buildah
  params:
  - name: app-name
    value: julians-express-app
  - name: source-repo
    value: "https://github.com/cloud-native-garage-method-cohort/julian-hahn-express-example"
  - name: image-repo
    value: quay.io/juhahn/express-sample-app
  workspaces: 
    - name: output
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi